import React from 'react';

export const contentData = {
  EN: {
    heroTitle: "Design Systems in the Age of AI",
    heroSubtitle: "From Interface to System Execution",
    heroPlaceholder: "AI-Detail-1440x810-Banner-Mp4",
    heroAspect: "16/9",
    sec1Title: "Redefining Design In The AI Era",
    sec1Desc: <>Redefine Design As Building AI-Driven <span className="font-bold">Experience Systems</span></>,
    sec1Placeholder: "AI Page -1140x290-A-EN-Png",
    sec1Aspect: "1140/290",
    sec2Title: "AI Capability Stack",
    sec2Desc: <>Form A Full-Stack System, AI Is Already Production-Ready<br />The <span className="font-bold">Key Is Orchestration</span></>,
    sec2Placeholder: "AI Page -1140x530-B-EN-Png",
    sec2Aspect: "1140/530",
    sec3Title: "From Page To Agent",
    sec3Desc: <>From Page To Agent, Products Are Shifting From UI-Driven To Task-Driven<br />Users No Longer Use Products, They Get Results From AI</>,
    sec3Placeholder: "AI Page -1140x170-C-EN-Png",
    sec3Aspect: "1140/170",
    sec4Title: "Redefining Design Responsibilities",
    sec4Desc: null,
    sec4Placeholder: "AI Page -1140x370-D-EN-Png",
    sec4Aspect: "1140/370",
    sec5Title: "New Design Outputs",
    sec5Desc: null,
    sec5Placeholder: "AI Page -1140x160-E-EN-Png",
    sec5Aspect: "1140/160",
    sec6Title: "How I Operationalize AI",
    sec6Desc: <>AI Is Implemented Across Three Layers<br />Design × Engineering × A</>,
    sec6Placeholder: "AI Page -1140x600-F-EN-Png",
    sec6Aspect: "1140/600",
    sec7Title: "Design Capabilities In The AI Era",
    sec7Desc: null,
    sec7Placeholder: "AI Page -1140x600-G-EN-Png",
    sec7Aspect: "1140/390",
  },
  CN: {
    heroTitle: "AI时代的设计系统与生产方式重构",
    heroSubtitle: "从界面设计 → AI工作流 → Agent执行系统",
    heroPlaceholder: "AI-Detail-1440x810-Banner-Mp4",
    heroAspect: "16/9",
    sec1Title: "AI时代下的设计新定义",
    sec1Desc: <>构建AI参与执行的体验生成系统</>,
    sec1Placeholder: "AI Page -1140x290-A-CN-Png",
    sec1Aspect: "1140/290",
    sec2Title: "AI技术能力结构",
    sec2Desc: <>AI已经具备端到端生产能力，关键在于系统整合与控制</>,
    sec2Placeholder: "AI Page -1140x510-B-CN-Png",
    sec2Aspect: "1140/510",
    sec3Title: "从页面到AGENT",
    sec3Desc: null,
    sec3Placeholder: "AI Page -1140x220-C-CN-Png",
    sec3Aspect: "1140/220",
    sec4Title: "设计职责的重构",
    sec4Desc: null,
    sec4Placeholder: "AI Page -1140x370-D-CN-Png",
    sec4Aspect: "1140/370",
    sec5Title: "新的设计产出",
    sec5Desc: null,
    sec5Placeholder: "AI Page -1140x160-E-CN-Png",
    sec5Aspect: "1140/160",
    sec6Title: "管理AI的核心--AI系统落地方式",
    sec6Desc: <>AI落地通过三个层面实现——设计 × 技术 × AI<br />核心是构建生产系统</>,
    sec6Placeholder: "AI Page -1140x520-F-CN-Png",
    sec6Aspect: "1140/520",
    sec7Title: "AI时代——我的设计新能力",
    sec7Desc: null,
    sec7Placeholder: "AI Page -1140x600-G-CN-Png",
    sec7Aspect: "1140/390",
  }
};
